# Generated by Django 5.2.8 on 2025-11-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('STATEMENT', 'Financial Statement'), ('TAX', 'Tax Document'), ('AUDIT', 'Audit Trail'), ('COMPLIANCE', 'Compliance Report'), ('CUSTOM', 'Custom Report')], max_length=20, verbose_name='report type')),
                ('report_format', models.CharField(choices=[('PDF', 'PDF'), ('EXCEL', 'Excel'), ('CSV', 'CSV')], max_length=10, verbose_name='report format')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('GENERATING', 'Generating'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='status')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/', verbose_name='file')),
                ('metadata', models.JSONField(default=dict, verbose_name='metadata')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_reports', to='groups.chamagroup')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'generated report',
                'verbose_name_plural': 'generated reports',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=20, verbose_name='report type')),
                ('report_format', models.CharField(max_length=10, verbose_name='report format')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('YEARLY', 'Yearly')], max_length=20, verbose_name='frequency')),
                ('recipients', models.JSONField(help_text='Email addresses', verbose_name='recipients')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('last_generated_at', models.DateTimeField(blank=True, null=True, verbose_name='last generated at')),
                ('next_generation_at', models.DateTimeField(verbose_name='next generation at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'scheduled report',
                'verbose_name_plural': 'scheduled reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
