# Generated by Django 5.2.8 on 2025-11-18 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalAPIConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('service_type', models.CharField(choices=[('BANK', 'Banking API'), ('CREDIT_BUREAU', 'Credit Bureau'), ('GOVERNMENT', 'Government Registry'), ('PAYMENT_GATEWAY', 'Payment Gateway'), ('OTHER', 'Other Service')], max_length=30, verbose_name='service type')),
                ('api_endpoint', models.URLField(verbose_name='API endpoint')),
                ('api_key', models.CharField(blank=True, max_length=500, verbose_name='API key')),
                ('credentials', models.JSONField(default=dict, help_text='Encrypted credentials', verbose_name='credentials')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ERROR', 'Error'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('health_check_url', models.URLField(blank=True, verbose_name='health check URL')),
                ('last_health_check', models.DateTimeField(blank=True, null=True, verbose_name='last health check')),
                ('rate_limit_per_minute', models.PositiveIntegerField(default=60, verbose_name='rate limit per minute')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'external API connection',
                'verbose_name_plural': 'external API connections',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('url', models.URLField(verbose_name='URL')),
                ('secret', models.CharField(help_text='Webhook signature secret', max_length=100, verbose_name='secret')),
                ('events', models.JSONField(help_text='List of events to subscribe to', verbose_name='events')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='headers')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('FAILED', 'Failed')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('retry_count', models.PositiveIntegerField(default=3, verbose_name='retry count')),
                ('last_triggered_at', models.DateTimeField(blank=True, null=True, verbose_name='last triggered at')),
                ('success_count', models.PositiveIntegerField(default=0, verbose_name='success count')),
                ('failure_count', models.PositiveIntegerField(default=0, verbose_name='failure count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'webhook endpoint',
                'verbose_name_plural': 'webhook endpoints',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='APIRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=500, verbose_name='endpoint')),
                ('method', models.CharField(max_length=10, verbose_name='method')),
                ('request_data', models.JSONField(blank=True, null=True, verbose_name='request data')),
                ('response_data', models.JSONField(blank=True, null=True, verbose_name='response data')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('TIMEOUT', 'Timeout'), ('RATE_LIMITED', 'Rate Limited')], max_length=20, verbose_name='status')),
                ('status_code', models.PositiveIntegerField(blank=True, null=True, verbose_name='status code')),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True, verbose_name='response time (ms)')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_requests', to='api_gateway.externalapiconnection')),
            ],
            options={
                'verbose_name': 'API request',
                'verbose_name_plural': 'API requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
