# Generated by Django 5.2.8 on 2025-11-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('EXPENSE', 'Expense'), ('LOAN_PAYMENT', 'Loan Payment')], max_length=20, verbose_name='transaction type')),
                ('transaction_data', models.JSONField(verbose_name='transaction data')),
                ('local_id', models.CharField(help_text='Client-generated ID', max_length=100, unique=True, verbose_name='local ID')),
                ('device_id', models.CharField(max_length=100, verbose_name='device ID')),
                ('status', models.CharField(choices=[('PENDING_SYNC', 'Pending Sync'), ('SYNCED', 'Synced'), ('CONFLICT', 'Conflict'), ('FAILED', 'Failed')], default='PENDING_SYNC', max_length=20, verbose_name='status')),
                ('server_id', models.PositiveIntegerField(blank=True, help_text='ID after sync', null=True, verbose_name='server ID')),
                ('created_at_device', models.DateTimeField(verbose_name='created at device')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('synced_at', models.DateTimeField(blank=True, null=True, verbose_name='synced at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'offline transaction',
                'verbose_name_plural': 'offline transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SyncConflict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conflict_type', models.CharField(max_length=50, verbose_name='conflict type')),
                ('conflict_details', models.JSONField(verbose_name='conflict details')),
                ('server_version', models.JSONField(verbose_name='server version')),
                ('client_version', models.JSONField(verbose_name='client version')),
                ('resolution_strategy', models.CharField(blank=True, choices=[('SERVER_WINS', 'Server Wins'), ('CLIENT_WINS', 'Client Wins'), ('MERGE', 'Merge'), ('MANUAL', 'Manual Resolution')], max_length=20, verbose_name='resolution strategy')),
                ('resolved_version', models.JSONField(blank=True, null=True, verbose_name='resolved version')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='detected at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('offline_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conflicts', to='mobile_sync.offlinetransaction')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'sync conflict',
                'verbose_name_plural': 'sync conflicts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSync',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100, verbose_name='device ID')),
                ('device_name', models.CharField(max_length=200, verbose_name='device name')),
                ('last_sync_at', models.DateTimeField(verbose_name='last sync at')),
                ('pending_items', models.PositiveIntegerField(default=0, verbose_name='pending items')),
                ('app_version', models.CharField(max_length=20, verbose_name='app version')),
                ('os_version', models.CharField(max_length=50, verbose_name='OS version')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='registered at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_syncs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'device sync',
                'verbose_name_plural': 'device syncs',
                'ordering': ['-last_sync_at'],
                'unique_together': {('user', 'device_id')},
            },
        ),
    ]
