# Generated by Django 5.2.8 on 2025-11-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KYCDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('NATIONAL_ID', 'National ID'), ('PASSPORT', 'Passport'), ('DRIVERS_LICENSE', 'Drivers License'), ('PROOF_OF_RESIDENCE', 'Proof of Residence'), ('BANK_STATEMENT', 'Bank Statement')], max_length=30, verbose_name='document type')),
                ('document_number', models.CharField(max_length=50, verbose_name='document number')),
                ('document_file', models.FileField(upload_to='kyc/', verbose_name='document file')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Verification'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired')], default='PENDING', max_length=20, verbose_name='status')),
                ('issue_date', models.DateField(verbose_name='issue date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='verified at')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='rejection reason')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kyc_documents', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC document',
                'verbose_name_plural': 'KYC documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='VerificationWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('DOCUMENTS_SUBMITTED', 'Documents Submitted'), ('UNDER_REVIEW', 'Under Review'), ('ADDITIONAL_INFO_REQUIRED', 'Additional Info Required'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='INITIATED', max_length=30, verbose_name='status')),
                ('documents_complete', models.BooleanField(default=False, verbose_name='documents complete')),
                ('biometric_complete', models.BooleanField(default=False, verbose_name='biometric complete')),
                ('compliance_check_complete', models.BooleanField(default=False, verbose_name='compliance check complete')),
                ('workflow_notes', models.TextField(blank=True, verbose_name='workflow notes')),
                ('reviewer_notes', models.TextField(blank=True, verbose_name='reviewer notes')),
                ('initiated_at', models.DateTimeField(auto_now_add=True, verbose_name='initiated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification_workflow', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'verification workflow',
                'verbose_name_plural': 'verification workflows',
                'ordering': ['-initiated_at'],
            },
        ),
        migrations.CreateModel(
            name='BiometricData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biometric_type', models.CharField(choices=[('FINGERPRINT', 'Fingerprint'), ('FACE', 'Face Recognition'), ('IRIS', 'Iris Scan')], max_length=20, verbose_name='biometric type')),
                ('biometric_hash', models.CharField(help_text='Encrypted biometric template', max_length=256, verbose_name='biometric hash')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='registered at')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='last used at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometric_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'biometric data',
                'verbose_name_plural': 'biometric data',
                'ordering': ['-registered_at'],
                'unique_together': {('user', 'biometric_type')},
            },
        ),
    ]
