# Generated by Django 5.2.8 on 2025-11-17 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[('FIXED_DEPOSIT', 'Fixed Deposit'), ('TREASURY_BILL', 'Treasury Bill'), ('MONEY_MARKET', 'Money Market Fund'), ('STOCKS', 'Stocks/Shares'), ('BONDS', 'Bonds'), ('REAL_ESTATE', 'Real Estate'), ('OTHER', 'Other')], max_length=30, verbose_name='investment type')),
                ('name', models.CharField(max_length=200, verbose_name='investment name')),
                ('description', models.TextField(verbose_name='description')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='principal amount')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='current value')),
                ('expected_return_rate', models.DecimalField(decimal_places=2, help_text='Expected annual return percentage', max_digits=5, verbose_name='expected return rate')),
                ('purchase_date', models.DateField(verbose_name='purchase date')),
                ('maturity_date', models.DateField(blank=True, null=True, verbose_name='maturity date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('MATURED', 'Matured'), ('SOLD', 'Sold'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('certificate', models.FileField(blank=True, null=True, upload_to='investments/certificates/', verbose_name='investment certificate')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_investments', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investments', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'investment',
                'verbose_name_plural': 'investments',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell'), ('DIVIDEND', 'Dividend'), ('INTEREST', 'Interest'), ('MATURITY', 'Maturity')], max_length=20, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='quantity')),
                ('price_per_unit', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price per unit')),
                ('transaction_date', models.DateField(verbose_name='transaction date')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='reference number')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_transactions', to=settings.AUTH_USER_MODEL)),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investment')),
            ],
            options={
                'verbose_name': 'investment transaction',
                'verbose_name_plural': 'investment transactions',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_invested', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='total invested')),
                ('current_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='current value')),
                ('stocks_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='stocks percentage')),
                ('bonds_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='bonds percentage')),
                ('real_estate_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='real estate percentage')),
                ('cash_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='cash percentage')),
                ('other_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='other percentage')),
                ('ytd_return', models.DecimalField(decimal_places=2, default=0.0, help_text='YTD return percentage', max_digits=8, verbose_name='year-to-date return')),
                ('last_rebalance_date', models.DateField(blank=True, null=True, verbose_name='last rebalance date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'portfolio',
                'verbose_name_plural': 'portfolios',
            },
        ),
        migrations.CreateModel(
            name='StockHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_symbol', models.CharField(help_text='e.g., SCOM for Safaricom', max_length=10, verbose_name='stock symbol')),
                ('stock_name', models.CharField(max_length=200, verbose_name='stock name')),
                ('exchange', models.CharField(default='NSE', help_text='e.g., NSE, USE', max_length=50, verbose_name='exchange')),
                ('shares_quantity', models.PositiveIntegerField(verbose_name='shares quantity')),
                ('purchase_price_per_share', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='purchase price per share')),
                ('current_price_per_share', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='current price per share')),
                ('cdsc_account_number', models.CharField(blank=True, max_length=50, verbose_name='CDSC account number')),
                ('total_purchase_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total purchase value')),
                ('current_total_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='current total value')),
                ('purchase_date', models.DateField(verbose_name='purchase date')),
                ('last_price_update', models.DateTimeField(auto_now=True, verbose_name='last price update')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_holdings', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'stock holding',
                'verbose_name_plural': 'stock holdings',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
