# Generated by Django 5.2.8 on 2025-11-17 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('OPERATIONAL', 'Operational'), ('ADMINISTRATIVE', 'Administrative'), ('WELFARE', 'Welfare'), ('INVESTMENT', 'Investment'), ('OTHER', 'Other')], max_length=20, verbose_name='category')),
                ('description', models.TextField(verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='expenses/receipts/', verbose_name='receipt')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('disbursed_at', models.DateTimeField(blank=True, null=True, verbose_name='disbursed at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='groups.chamagroup')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'expense',
                'verbose_name_plural': 'expenses',
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='principal amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual interest rate in percentage', max_digits=5, verbose_name='interest rate')),
                ('duration_months', models.PositiveIntegerField(verbose_name='duration (months)')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Principal + Interest', max_digits=12, verbose_name='total amount')),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='monthly payment')),
                ('outstanding_balance', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='outstanding balance')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('DISBURSED', 'Disbursed'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DEFAULTED', 'Defaulted'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status')),
                ('purpose', models.TextField(help_text='Reason for loan', verbose_name='purpose')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='applied at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('disbursed_at', models.DateTimeField(blank=True, null=True, verbose_name='disbursed at')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_loans', to=settings.AUTH_USER_MODEL)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='DisbursementApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_type', models.CharField(choices=[('LOAN', 'Loan Disbursement'), ('EXPENSE', 'Expense'), ('WITHDRAWAL', 'Withdrawal')], max_length=20, verbose_name='approval type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('description', models.TextField(verbose_name='description')),
                ('required_approvals', models.PositiveIntegerField(default=2, verbose_name='required approvals')),
                ('approvals_count', models.PositiveIntegerField(default=0, verbose_name='approvals count')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='groups.chamagroup')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_approvals', to=settings.AUTH_USER_MODEL)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='finance.expense')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='finance.loan')),
            ],
            options={
                'verbose_name': 'disbursement approval',
                'verbose_name_plural': 'disbursement approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('payment_method', models.CharField(max_length=20, verbose_name='payment method')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='reference number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PENDING', max_length=20, verbose_name='status')),
                ('paid_at', models.DateTimeField(auto_now_add=True, verbose_name='paid at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='finance.loan')),
            ],
            options={
                'verbose_name': 'loan repayment',
                'verbose_name_plural': 'loan repayments',
                'ordering': ['-paid_at'],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('payment_method', models.CharField(choices=[('MPESA', 'M-Pesa'), ('BANK', 'Bank Transfer'), ('CASH', 'Cash'), ('OTHER', 'Other')], max_length=20, verbose_name='payment method')),
                ('reference_number', models.CharField(blank=True, max_length=100, verbose_name='reference number')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('RECONCILED', 'Reconciled')], default='PENDING', max_length=20, verbose_name='status')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='reconciled at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='groups.chamagroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to=settings.AUTH_USER_MODEL)),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_contributions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contribution',
                'verbose_name_plural': 'contributions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['group', 'member'], name='finance_con_group_i_7d85c6_idx'), models.Index(fields=['status'], name='finance_con_status_6428eb_idx'), models.Index(fields=['created_at'], name='finance_con_created_2f84c7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ApprovalSignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False, verbose_name='approved')),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
                ('signed_at', models.DateTimeField(auto_now_add=True, verbose_name='signed at')),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_signatures', to=settings.AUTH_USER_MODEL)),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='finance.disbursementapproval')),
            ],
            options={
                'verbose_name': 'approval signature',
                'verbose_name_plural': 'approval signatures',
                'ordering': ['-signed_at'],
                'unique_together': {('approval', 'approver')},
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['group', 'borrower'], name='finance_loa_group_i_9b2d88_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['status'], name='finance_loa_status_ba862c_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['applied_at'], name='finance_loa_applied_698167_idx'),
        ),
    ]
