# Generated by Django 5.2.8 on 2025-11-21 17:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.0'), help_text='Annual interest rate in percentage (defaults to 10%)', max_digits=5, verbose_name='interest rate'),
        ),
    ]
