# Generated by Django 5.2.8 on 2025-11-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(help_text='Score between 300-850', verbose_name='credit score')),
                ('score_grade', models.CharField(choices=[('EXCELLENT', 'Excellent (750+)'), ('GOOD', 'Good (650-749)'), ('FAIR', 'Fair (550-649)'), ('POOR', 'Poor (450-549)'), ('VERY_POOR', 'Very Poor (<450)')], max_length=20, verbose_name='score grade')),
                ('payment_history_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='payment history score')),
                ('contribution_consistency_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='contribution consistency score')),
                ('debt_to_income_ratio', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='debt to income ratio')),
                ('loan_repayment_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='loan repayment rate')),
                ('membership_duration_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='membership duration score')),
                ('default_probability', models.DecimalField(decimal_places=2, help_text='Probability percentage', max_digits=5, verbose_name='default probability')),
                ('recommended_credit_limit', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='recommended credit limit')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='calculated at')),
                ('expires_at', models.DateTimeField(help_text='Score validity period', verbose_name='expires at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_credit_scores', to='groups.chamagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'credit score',
                'verbose_name_plural': 'credit scores',
                'ordering': ['-calculated_at'],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='DefaultPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_probability', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='default probability')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk'), ('VERY_HIGH', 'Very High Risk')], max_length=20, verbose_name='risk level')),
                ('confidence_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='confidence score')),
                ('key_risk_factors', models.JSONField(verbose_name='key risk factors')),
                ('mitigation_recommendations', models.TextField(verbose_name='mitigation recommendations')),
                ('predicted_at', models.DateTimeField(auto_now_add=True, verbose_name='predicted at')),
                ('model_version', models.CharField(default='1.0', max_length=20, verbose_name='model version')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_predictions', to='finance.loan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'default prediction',
                'verbose_name_plural': 'default predictions',
                'ordering': ['-predicted_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='requested amount')),
                ('maximum_eligible_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='maximum eligible amount')),
                ('status', models.CharField(choices=[('ELIGIBLE', 'Eligible'), ('NOT_ELIGIBLE', 'Not Eligible'), ('CONDITIONAL', 'Conditionally Eligible')], max_length=20, verbose_name='status')),
                ('eligibility_reasons', models.JSONField(help_text='Detailed reasons for decision', verbose_name='eligibility reasons')),
                ('conditions', models.TextField(blank=True, help_text='Conditions if conditionally eligible', verbose_name='conditions')),
                ('checked_at', models.DateTimeField(auto_now_add=True, verbose_name='checked at')),
                ('credit_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_checks', to='credit_scoring.creditscore')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_eligibilities', to='groups.chamagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_eligibilities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'loan eligibility',
                'verbose_name_plural': 'loan eligibilities',
                'ordering': ['-checked_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentHistoryAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_payments', models.PositiveIntegerField(verbose_name='total payments')),
                ('on_time_payments', models.PositiveIntegerField(verbose_name='on-time payments')),
                ('late_payments', models.PositiveIntegerField(verbose_name='late payments')),
                ('missed_payments', models.PositiveIntegerField(verbose_name='missed payments')),
                ('average_payment_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='average payment amount')),
                ('payment_consistency_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='payment consistency rate')),
                ('late_payment_rate', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='late payment rate')),
                ('analysis_period_months', models.PositiveIntegerField(verbose_name='analysis period (months)')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='analyzed at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_analyses', to='groups.chamagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment history analysis',
                'verbose_name_plural': 'payment history analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
    ]
