# analytics_dashboard/models.py
from django.db import models
from django.conf import settings
from django.utils.translation import gettext_lazy as _
from django.core.validators import MinValueValidator, MaxValueValidator


class AnalyticsReport(models.Model):
    """Pre-computed analytics reports including full dashboard JSON."""
    
    class ReportType(models.TextChoices):
        FINANCIAL_HEALTH = 'FINANCIAL_HEALTH', _('Financial Health')
        CONTRIBUTION_TRENDS = 'CONTRIBUTION_TRENDS', _('Contribution Trends')
        MEMBER_ENGAGEMENT = 'MEMBER_ENGAGEMENT', _('Member Engagement')
        CASH_FLOW = 'CASH_FLOW', _('Cash Flow Analysis')
        DASHBOARD_SUMMARY = 'DASHBOARD_SUMMARY', _('Dashboard Summary')  # Used by frontend

    group = models.ForeignKey(
        'groups.ChamaGroup',
        on_delete=models.CASCADE,
        related_name='analytics_reports',
        verbose_name=_('chama group')
    )
    report_type = models.CharField(
        max_length=30,
        choices=ReportType.choices,
        verbose_name=_('report type')
    )
    report_data = models.JSONField(
        _('report data'),
        help_text=_('Pre-computed chart-ready JSON data')
    )
    insights = models.TextField(_('insights'), blank=True)
    recommendations = models.TextField(_('recommendations'), blank=True)

    generated_at = models.DateTimeField(_('generated at'), auto_now_add=True, db_index=True)
    generated_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        verbose_name=_('generated by')
    )

    class Meta:
        verbose_name = _('analytics report')
        verbose_name_plural = _('analytics reports')
        ordering = ['-generated_at']
        unique_together = ['group', 'report_type']  # One latest per type per group
        indexes = [
            models.Index(fields=['group', 'report_type']),
            models.Index(fields=['-generated_at']),
        ]

    def __str__(self):
        return f"{self.get_report_type_display()} • {self.group.name}"


class FinancialHealthScore(models.Model):
    """Overall financial health score (0–100) with breakdown."""
    group = models.ForeignKey(
        'groups.ChamaGroup',
        on_delete=models.CASCADE,
        related_name='health_scores'
    )
    overall_score = models.PositiveSmallIntegerField(
        _('overall score'),
        validators=[MinValueValidator(0), MaxValueValidator(100)]
    )
    liquidity_score = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    growth_score = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    stability_score = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    engagement_score = models.PositiveSmallIntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])

    trends = models.JSONField(_('historical trends'), default=dict)
    calculated_at = models.DateTimeField(_('calculated at'), auto_now_add=True, db_index=True)

    class Meta:
        verbose_name = _('financial health score')
        verbose_name_plural = _('financial health scores')
        ordering = ['-calculated_at']
        indexes = [models.Index(fields=['group', '-calculated_at'])]

    def __str__(self):
        return f"{self.group.name} • {self.overall_score}/100"

# Add this to the bottom of analytics_dashboard/models.py

class PredictiveCashFlow(models.Model):
    """Future: AI-powered cash flow forecasting"""
    group = models.ForeignKey(
        'groups.ChamaGroup',
        on_delete=models.CASCADE,
        related_name='cash_flow_predictions'
    )
    prediction_month = models.DateField(_('prediction for month'))
    predicted_inflow = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    predicted_outflow = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    predicted_balance = models.DecimalField(max_digits=15, decimal_places=2, default=0)
    confidence_score = models.FloatField(default=0.0)  # 0–100
    generated_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = "Predictive Cash Flow"
        ordering = ['-prediction_month']

    def __str__(self):
        return f"{self.group.name} – {self.prediction_month.strftime('%B %Y')}"
