# Generated by Django 5.2.8 on 2025-11-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='title')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='started at')),
                ('last_message_at', models.DateTimeField(auto_now=True, verbose_name='last message at')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_conversations', to='groups.chamagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chat conversation',
                'verbose_name_plural': 'chat conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('USER', 'User'), ('ASSISTANT', 'Assistant'), ('SYSTEM', 'System')], max_length=20, verbose_name='role')),
                ('content', models.TextField(verbose_name='content')),
                ('intent', models.CharField(blank=True, help_text='Detected user intent', max_length=50, verbose_name='intent')),
                ('confidence', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='confidence')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='ai_assistant.chatconversation')),
            ],
            options={
                'verbose_name': 'chat message',
                'verbose_name_plural': 'chat messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialAdvice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice_type', models.CharField(choices=[('SAVINGS', 'Savings Strategy'), ('INVESTMENT', 'Investment Recommendation'), ('LOAN', 'Loan Guidance'), ('BUDGETING', 'Budgeting Tips')], max_length=20, verbose_name='advice type')),
                ('advice_content', models.TextField(verbose_name='advice content')),
                ('action_items', models.JSONField(default=list, verbose_name='action items')),
                ('relevance_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='relevance score')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='generated at')),
                ('user_feedback', models.CharField(blank=True, choices=[('HELPFUL', 'Helpful'), ('NOT_HELPFUL', 'Not Helpful')], max_length=20, verbose_name='user feedback')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.chamagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_advice', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'financial advice',
                'verbose_name_plural': 'financial advice',
                'ordering': ['-generated_at'],
            },
        ),
    ]
