# Generated by Django 5.2.8 on 2025-11-17 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odpc_registered', models.BooleanField(default=False, verbose_name='ODPC registered')),
                ('odpc_registration_number', models.CharField(blank=True, max_length=100, verbose_name='ODPC registration number')),
                ('aml_kyc_compliant', models.BooleanField(default=False, verbose_name='AML/KYC compliant')),
                ('security_certified', models.BooleanField(default=False, verbose_name='security certified')),
                ('certification_type', models.CharField(blank=True, help_text='e.g., ISO 27001', max_length=100, verbose_name='certification type')),
                ('overall_status', models.CharField(choices=[('COMPLIANT', 'Compliant'), ('NON_COMPLIANT', 'Non-Compliant'), ('PENDING', 'Pending')], default='PENDING', max_length=20, verbose_name='overall status')),
                ('compliance_certificate', models.FileField(blank=True, null=True, upload_to='governance/compliance/', verbose_name='compliance certificate')),
                ('last_audit_date', models.DateField(blank=True, null=True, verbose_name='last audit date')),
                ('next_audit_date', models.DateField(blank=True, null=True, verbose_name='next audit date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_records', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'compliance record',
                'verbose_name_plural': 'compliance records',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('document_type', models.CharField(choices=[('MEETING_MINUTES', 'Meeting Minutes'), ('FINANCIAL_STATEMENT', 'Financial Statement'), ('CONSTITUTION', 'Constitution'), ('POLICY', 'Policy Document'), ('REPORT', 'Report'), ('OTHER', 'Other')], max_length=30, verbose_name='document type')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('file', models.FileField(upload_to='governance/documents/', verbose_name='file')),
                ('is_public', models.BooleanField(default=False, help_text='Visible to all members', verbose_name='is public')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='file size (bytes)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='groups.chamagroup')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'document',
                'verbose_name_plural': 'documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Fine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine_type', models.CharField(choices=[('LATE_CONTRIBUTION', 'Late Contribution'), ('MISSED_MEETING', 'Missed Meeting'), ('BREACH_OF_RULES', 'Breach of Rules'), ('OTHER', 'Other')], max_length=30, verbose_name='fine type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='amount')),
                ('reason', models.TextField(verbose_name='reason')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAIVED', 'Waived')], default='PENDING', max_length=20, verbose_name='status')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='issued at')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('waived_at', models.DateTimeField(blank=True, null=True, verbose_name='waived at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to='groups.chamagroup')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_fines', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fines', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'fine',
                'verbose_name_plural': 'fines',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupConstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Group Constitution', max_length=200, verbose_name='title')),
                ('content', models.TextField(help_text='Full constitution text', verbose_name='content')),
                ('membership_rules', models.TextField(blank=True, verbose_name='membership rules')),
                ('contribution_rules', models.TextField(blank=True, verbose_name='contribution rules')),
                ('loan_policy', models.TextField(blank=True, verbose_name='loan policy')),
                ('exit_procedure', models.TextField(blank=True, verbose_name='exit procedure')),
                ('late_contribution_fine', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='late contribution fine')),
                ('missed_meeting_fine', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='missed meeting fine')),
                ('constitution_document', models.FileField(blank=True, null=True, upload_to='governance/constitutions/', verbose_name='constitution document')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_constitutions', to=settings.AUTH_USER_MODEL)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='constitution', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'group constitution',
                'verbose_name_plural': 'group constitutions',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('vote_type', models.CharField(choices=[('SIMPLE', 'Simple Majority'), ('TWO_THIRDS', 'Two-Thirds Majority'), ('UNANIMOUS', 'Unanimous')], default='SIMPLE', max_length=20, verbose_name='vote type')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20, verbose_name='status')),
                ('allow_proxy', models.BooleanField(default=True, verbose_name='allow proxy voting')),
                ('start_date', models.DateTimeField(verbose_name='start date')),
                ('end_date', models.DateTimeField(verbose_name='end date')),
                ('total_eligible_voters', models.PositiveIntegerField(default=0, verbose_name='total eligible voters')),
                ('total_votes_cast', models.PositiveIntegerField(default=0, verbose_name='total votes cast')),
                ('yes_votes', models.PositiveIntegerField(default=0, verbose_name='yes votes')),
                ('no_votes', models.PositiveIntegerField(default=0, verbose_name='no votes')),
                ('abstain_votes', models.PositiveIntegerField(default=0, verbose_name='abstain votes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_votes', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'vote',
                'verbose_name_plural': 'votes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VoteBallot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No'), ('ABSTAIN', 'Abstain')], max_length=10, verbose_name='choice')),
                ('is_proxy', models.BooleanField(default=False, verbose_name='is proxy vote')),
                ('cast_at', models.DateTimeField(auto_now_add=True, verbose_name='cast at')),
                ('comments', models.TextField(blank=True, verbose_name='comments')),
                ('proxy_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proxy_votes', to=settings.AUTH_USER_MODEL)),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ballots', to='governance.vote')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_ballots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'vote ballot',
                'verbose_name_plural': 'vote ballots',
                'ordering': ['-cast_at'],
                'unique_together': {('vote', 'voter')},
            },
        ),
    ]
