# Generated by Django 5.2.8 on 2025-11-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('FINANCIAL_HEALTH', 'Financial Health'), ('CONTRIBUTION_TRENDS', 'Contribution Trends'), ('MEMBER_ENGAGEMENT', 'Member Engagement'), ('CASH_FLOW', 'Cash Flow Analysis')], max_length=30, verbose_name='report type')),
                ('report_data', models.JSONField(verbose_name='report data')),
                ('insights', models.TextField(verbose_name='insights')),
                ('recommendations', models.TextField(blank=True, verbose_name='recommendations')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='generated at')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'analytics report',
                'verbose_name_plural': 'analytics reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='FinancialHealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.PositiveIntegerField(help_text='Score out of 100', verbose_name='overall score')),
                ('liquidity_score', models.PositiveIntegerField(verbose_name='liquidity score')),
                ('growth_score', models.PositiveIntegerField(verbose_name='growth score')),
                ('stability_score', models.PositiveIntegerField(verbose_name='stability score')),
                ('engagement_score', models.PositiveIntegerField(verbose_name='engagement score')),
                ('trends', models.JSONField(help_text='Historical trend data', verbose_name='trends')),
                ('calculated_at', models.DateTimeField(auto_now_add=True, verbose_name='calculated at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'financial health score',
                'verbose_name_plural': 'financial health scores',
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictiveCashFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction_month', models.DateField(verbose_name='prediction month')),
                ('predicted_inflow', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='predicted inflow')),
                ('predicted_outflow', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='predicted outflow')),
                ('predicted_balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='predicted balance')),
                ('confidence_level', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='confidence level')),
                ('model_accuracy', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='model accuracy')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_flow_predictions', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'predictive cash flow',
                'verbose_name_plural': 'predictive cash flows',
                'ordering': ['-prediction_month'],
            },
        ),
    ]
