# Generated by Django 5.2.8 on 2025-11-18 19:27

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics_dashboard', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='predictivecashflow',
            options={'ordering': ['-prediction_month'], 'verbose_name': 'Predictive Cash Flow'},
        ),
        migrations.RemoveField(
            model_name='predictivecashflow',
            name='confidence_level',
        ),
        migrations.RemoveField(
            model_name='predictivecashflow',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='predictivecashflow',
            name='model_accuracy',
        ),
        migrations.AddField(
            model_name='predictivecashflow',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='predictivecashflow',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='analyticsreport',
            name='generated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='generated at'),
        ),
        migrations.AlterField(
            model_name='analyticsreport',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='generated by'),
        ),
        migrations.AlterField(
            model_name='analyticsreport',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_reports', to='groups.chamagroup', verbose_name='chama group'),
        ),
        migrations.AlterField(
            model_name='analyticsreport',
            name='insights',
            field=models.TextField(blank=True, verbose_name='insights'),
        ),
        migrations.AlterField(
            model_name='analyticsreport',
            name='report_data',
            field=models.JSONField(help_text='Pre-computed chart-ready JSON data', verbose_name='report data'),
        ),
        migrations.AlterField(
            model_name='analyticsreport',
            name='report_type',
            field=models.CharField(choices=[('FINANCIAL_HEALTH', 'Financial Health'), ('CONTRIBUTION_TRENDS', 'Contribution Trends'), ('MEMBER_ENGAGEMENT', 'Member Engagement'), ('CASH_FLOW', 'Cash Flow Analysis'), ('DASHBOARD_SUMMARY', 'Dashboard Summary')], max_length=30, verbose_name='report type'),
        ),
        migrations.AlterField(
            model_name='financialhealthscore',
            name='calculated_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='calculated at'),
        ),
        migrations.AlterField(
            model_name='financialhealthscore',
            name='engagement_score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='financialhealthscore',
            name='growth_score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='financialhealthscore',
            name='liquidity_score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='financialhealthscore',
            name='overall_score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='overall score'),
        ),
        migrations.AlterField(
            model_name='financialhealthscore',
            name='stability_score',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='financialhealthscore',
            name='trends',
            field=models.JSONField(default=dict, verbose_name='historical trends'),
        ),
        migrations.AlterField(
            model_name='predictivecashflow',
            name='predicted_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='predictivecashflow',
            name='predicted_inflow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='predictivecashflow',
            name='predicted_outflow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='predictivecashflow',
            name='prediction_month',
            field=models.DateField(verbose_name='prediction for month'),
        ),
        migrations.AlterUniqueTogether(
            name='analyticsreport',
            unique_together={('group', 'report_type')},
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['group', 'report_type'], name='analytics_d_group_i_a7e6b6_idx'),
        ),
        migrations.AddIndex(
            model_name='analyticsreport',
            index=models.Index(fields=['-generated_at'], name='analytics_d_generat_99cf68_idx'),
        ),
        migrations.AddIndex(
            model_name='financialhealthscore',
            index=models.Index(fields=['group', '-calculated_at'], name='analytics_d_group_i_f836e1_idx'),
        ),
    ]
