# Generated by Django 5.2.8 on 2025-11-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(max_length=50, verbose_name='report type')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('findings', models.JSONField(verbose_name='findings')),
                ('recommendations', models.TextField(blank=True, verbose_name='recommendations')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('SUBMITTED', 'Submitted to Authorities')], default='PENDING', max_length=20, verbose_name='status')),
                ('file', models.FileField(blank=True, null=True, upload_to='compliance/', verbose_name='file')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='generated at')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='submitted at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_reports', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'compliance report',
                'verbose_name_plural': 'compliance reports',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousActivityAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=50, verbose_name='alert type')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=20, verbose_name='severity')),
                ('description', models.TextField(verbose_name='description')),
                ('detection_details', models.JSONField(verbose_name='detection details')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved'), ('FALSE_POSITIVE', 'False Positive')], default='NEW', max_length=20, verbose_name='status')),
                ('resolution_notes', models.TextField(blank=True, verbose_name='resolution notes')),
                ('detected_at', models.DateTimeField(auto_now_add=True, verbose_name='detected at')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='resolved at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspicious_alerts', to='groups.chamagroup')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_alerts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suspicious_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'suspicious activity alert',
                'verbose_name_plural': 'suspicious activity alerts',
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('APPROVE', 'Approve'), ('REJECT', 'Reject'), ('TRANSFER', 'Transfer')], max_length=20, verbose_name='action type')),
                ('entity_type', models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('LOAN', 'Loan'), ('EXPENSE', 'Expense'), ('INVESTMENT', 'Investment'), ('USER', 'User'), ('GROUP', 'Group')], max_length=20, verbose_name='entity type')),
                ('entity_id', models.PositiveIntegerField(verbose_name='entity ID')),
                ('changes', models.JSONField(help_text='Old and new values', verbose_name='changes')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
                ('checksum', models.CharField(help_text='SHA-256 hash for integrity', max_length=64, verbose_name='checksum')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id'], name='audit_trail_entity__d05775_idx'), models.Index(fields=['user', 'timestamp'], name='audit_trail_user_id_d64fec_idx')],
            },
        ),
    ]
