# Generated by Django 5.2.8 on 2025-11-17 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChamaGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='group name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('group_type', models.CharField(choices=[('SAVINGS', 'Savings Group'), ('INVESTMENT', 'Investment Group'), ('WELFARE', 'Welfare Group'), ('MIXED', 'Mixed Purpose')], default='SAVINGS', max_length=20, verbose_name='group type')),
                ('objectives', models.TextField(help_text='Group goals and objectives', verbose_name='objectives')),
                ('registration_certificate', models.FileField(blank=True, null=True, upload_to='groups/kyb/certificates/', verbose_name='registration certificate')),
                ('kra_pin', models.CharField(blank=True, max_length=20, verbose_name='KRA PIN')),
                ('kra_document', models.FileField(blank=True, null=True, upload_to='groups/kyb/kra/', verbose_name='KRA document')),
                ('articles_of_association', models.FileField(blank=True, null=True, upload_to='groups/kyb/articles/', verbose_name='articles of association')),
                ('contribution_frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', max_length=20, verbose_name='contribution frequency')),
                ('minimum_contribution', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='minimum contribution')),
                ('total_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='total balance')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('kyb_verified', models.BooleanField(default=False, verbose_name='KYB verified')),
                ('kyb_verified_at', models.DateTimeField(blank=True, null=True, verbose_name='KYB verified at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chama group',
                'verbose_name_plural': 'chama groups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='target amount')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, verbose_name='current amount')),
                ('target_date', models.DateField(verbose_name='target date')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('ACHIEVED', 'Achieved'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('achieved_at', models.DateTimeField(blank=True, null=True, verbose_name='achieved at')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'group goal',
                'verbose_name_plural': 'group goals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('CHAIRPERSON', 'Chairperson'), ('TREASURER', 'Treasurer'), ('SECRETARY', 'Secretary'), ('MEMBER', 'Member')], default='MEMBER', max_length=20, verbose_name='role')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXITED', 'Exited')], default='PENDING', max_length=20, verbose_name='status')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='approved at')),
                ('exited_at', models.DateTimeField(blank=True, null=True, verbose_name='exited at')),
                ('total_contributions', models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='total contributions')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.chamagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'group membership',
                'verbose_name_plural': 'group memberships',
                'ordering': ['-joined_at'],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='GroupOfficial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('CHAIRPERSON', 'Chairperson'), ('VICE_CHAIRPERSON', 'Vice Chairperson'), ('TREASURER', 'Treasurer'), ('SECRETARY', 'Secretary'), ('ORGANIZING_SECRETARY', 'Organizing Secretary')], max_length=30, verbose_name='position')),
                ('elected_at', models.DateTimeField(auto_now_add=True, verbose_name='elected at')),
                ('term_start', models.DateField(verbose_name='term start')),
                ('term_end', models.DateField(verbose_name='term end')),
                ('is_current', models.BooleanField(default=True, verbose_name='is current')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='groups.chamagroup')),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_positions', to='groups.groupmembership')),
            ],
            options={
                'verbose_name': 'group official',
                'verbose_name_plural': 'group officials',
                'ordering': ['-elected_at'],
                'unique_together': {('group', 'position', 'is_current')},
            },
        ),
    ]
