# Generated by Django 5.2.8 on 2025-11-19 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='content')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='groups/messages/attachments/', verbose_name='attachment')),
                ('attachment_name', models.CharField(blank=True, max_length=255, verbose_name='attachment name')),
                ('is_edited', models.BooleanField(default=False, verbose_name='is edited')),
                ('edited_at', models.DateTimeField(blank=True, null=True, verbose_name='edited at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groups.chamagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'group message',
                'verbose_name_plural': 'group messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['group', 'created_at'], name='groups_grou_group_i_7da147_idx'), models.Index(fields=['user', 'created_at'], name='groups_grou_user_id_3ed02f_idx')],
            },
        ),
    ]
