# Generated by Django 5.2.8 on 2025-12-15 14:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_groupmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='chamagroup',
            name='articles_of_association',
            field=models.FileField(blank=True, help_text='Legal document outlining group rules and structure', null=True, upload_to='groups/kyb/articles/', verbose_name='articles of association'),
        ),
        migrations.AlterField(
            model_name='chamagroup',
            name='contribution_frequency',
            field=models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Bi-Weekly'), ('MONTHLY', 'Monthly')], default='MONTHLY', help_text='How often members are expected to contribute', max_length=20, verbose_name='contribution frequency'),
        ),
        migrations.AlterField(
            model_name='chamagroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the group was created', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='chamagroup',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this group', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chamagroup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Whether the group is currently active and accepting contributions', verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='chamagroup',
            name='kra_document',
            field=models.FileField(blank=True, help_text='KRA registration or tax compliance document', null=True, upload_to='groups/kyb/kra/', verbose_name='KRA document'),
        ),
        migrations.AlterField(
            model_name='chamagroup',
            name='kra_pin',
            field=models.CharField(blank=True, help_text='Kenya Revenue Authority Personal Identification Number', max_length=20, verbose_name='KRA PIN'),
        ),
        migrations.AlterField(
            model_name='chamagroup',
            name='kyb_verified',
            field=models.BooleanField(default=False, help_text='Whether the group has completed KYB verification', verbose_name='KYB verified'),
        ),
        migrations.AlterField(
            model_name='chamagroup',
            name='kyb_verified_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when KYB verification was completed', null=True, verbose_name='KYB verified at'),
        ),
        migrations.AlterField(
            model_name='chamagroup',
            name='minimum_contribution',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum amount required per contribution period', max_digits=10, verbose_name='minimum contribution'),
        ),
        migrations.AlterField(
            model_name='chamagroup',
            name='registration_certificate',
            field=models.FileField(blank=True, help_text='Official business registration certificate', null=True, upload_to='groups/kyb/certificates/', verbose_name='registration certificate'),
        ),
        migrations.AlterField(
            model_name='chamagroup',
            name='total_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current total funds available in the group', max_digits=15, verbose_name='total balance'),
        ),
        migrations.AlterField(
            model_name='chamagroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the group was last updated', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='groupgoal',
            name='achieved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the goal was achieved', null=True, verbose_name='achieved at'),
        ),
        migrations.AlterField(
            model_name='groupgoal',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the goal was created', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='groupgoal',
            name='created_by',
            field=models.ForeignKey(help_text='User who created this goal', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupgoal',
            name='current_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current amount saved toward the goal', max_digits=15, verbose_name='current amount'),
        ),
        migrations.AlterField(
            model_name='groupgoal',
            name='description',
            field=models.TextField(help_text='Detailed description of what the goal aims to achieve', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='groupgoal',
            name='group',
            field=models.ForeignKey(help_text='The group this goal belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='groups.chamagroup'),
        ),
        migrations.AlterField(
            model_name='groupgoal',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ACHIEVED', 'Achieved'), ('CANCELLED', 'Cancelled')], default='ACTIVE', help_text='Current status of the goal', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='groupgoal',
            name='target_amount',
            field=models.DecimalField(decimal_places=2, help_text='Financial target amount for the goal', max_digits=15, verbose_name='target amount'),
        ),
        migrations.AlterField(
            model_name='groupgoal',
            name='target_date',
            field=models.DateField(help_text='Target date for achieving the goal', verbose_name='target date'),
        ),
        migrations.AlterField(
            model_name='groupgoal',
            name='title',
            field=models.CharField(help_text='Name or title of the goal', max_length=200, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='groupgoal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when the goal was last updated', verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the membership was approved', null=True, verbose_name='approved at'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='exited_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the user left the group', null=True, verbose_name='exited at'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='group',
            field=models.ForeignKey(help_text='The group this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='groups.chamagroup'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='joined_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the user joined or requested to join', verbose_name='joined at'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('CHAIRPERSON', 'Chairperson'), ('TREASURER', 'Treasurer'), ('SECRETARY', 'Secretary'), ('MEMBER', 'Member')], default='MEMBER', help_text='User role within the group', max_length=20, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('EXITED', 'Exited')], default='PENDING', help_text='Current status of the membership', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='total_contributions',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total amount contributed by this member to the group', max_digits=12, verbose_name='total contributions'),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(help_text='The user who is a member of the group', on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='groups/messages/attachments/', verbose_name='attachment'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='attachment_name',
            field=models.CharField(blank=True, help_text='Original name of the attached file', max_length=255, verbose_name='attachment name'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='content',
            field=models.TextField(help_text='Text content of the message', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the message was sent', verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='edited_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the message was last edited', null=True, verbose_name='edited at'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='group',
            field=models.ForeignKey(help_text='The group this message belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='groups.chamagroup'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='is_edited',
            field=models.BooleanField(default=False, help_text='Whether this message has been edited', verbose_name='is edited'),
        ),
        migrations.AlterField(
            model_name='groupmessage',
            name='user',
            field=models.ForeignKey(help_text='User who sent this message', on_delete=django.db.models.deletion.CASCADE, related_name='group_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='groupofficial',
            name='elected_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the official was elected or appointed', verbose_name='elected at'),
        ),
        migrations.AlterField(
            model_name='groupofficial',
            name='group',
            field=models.ForeignKey(help_text='The group this official serves in', on_delete=django.db.models.deletion.CASCADE, related_name='officials', to='groups.chamagroup'),
        ),
        migrations.AlterField(
            model_name='groupofficial',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Whether this is the current official for this position', verbose_name='is current'),
        ),
        migrations.AlterField(
            model_name='groupofficial',
            name='membership',
            field=models.ForeignKey(help_text='The member who holds this official position', on_delete=django.db.models.deletion.CASCADE, related_name='official_positions', to='groups.groupmembership'),
        ),
        migrations.AlterField(
            model_name='groupofficial',
            name='position',
            field=models.CharField(choices=[('CHAIRPERSON', 'Chairperson'), ('VICE_CHAIRPERSON', 'Vice Chairperson'), ('TREASURER', 'Treasurer'), ('SECRETARY', 'Secretary'), ('ORGANIZING_SECRETARY', 'Organizing Secretary')], help_text='Official position within the group', max_length=30, verbose_name='position'),
        ),
        migrations.AlterField(
            model_name='groupofficial',
            name='term_end',
            field=models.DateField(help_text='End date of the official term', verbose_name='term end'),
        ),
        migrations.AlterField(
            model_name='groupofficial',
            name='term_start',
            field=models.DateField(help_text='Start date of the official term', verbose_name='term start'),
        ),
        migrations.AddIndex(
            model_name='chamagroup',
            index=models.Index(fields=['created_by', 'created_at'], name='groups_cham_created_6cb2a4_idx'),
        ),
        migrations.AddIndex(
            model_name='chamagroup',
            index=models.Index(fields=['is_active', 'kyb_verified'], name='groups_cham_is_acti_27857b_idx'),
        ),
        migrations.AddIndex(
            model_name='groupgoal',
            index=models.Index(fields=['group', 'status'], name='groups_grou_group_i_ed69aa_idx'),
        ),
        migrations.AddIndex(
            model_name='groupgoal',
            index=models.Index(fields=['target_date', 'status'], name='groups_grou_target__6a522a_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['group', 'status'], name='groups_grou_group_i_d0a4fa_idx'),
        ),
        migrations.AddIndex(
            model_name='groupmembership',
            index=models.Index(fields=['user', 'status'], name='groups_grou_user_id_fbaf63_idx'),
        ),
        migrations.AddIndex(
            model_name='groupofficial',
            index=models.Index(fields=['group', 'is_current'], name='groups_grou_group_i_56e84a_idx'),
        ),
        migrations.AddIndex(
            model_name='groupofficial',
            index=models.Index(fields=['membership', 'is_current'], name='groups_grou_members_c062b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='chamagroup',
            constraint=models.UniqueConstraint(condition=models.Q(('created_by__isnull', False)), fields=('name', 'created_by'), name='unique_group_name_per_creator', violation_error_message='You already have a group with this name. Please choose a different name.'),
        ),
    ]
