# Generated by Django 5.2.8 on 2025-11-18 12:40

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0001_initial'),
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MPesaBulkPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=100, unique=True, verbose_name='batch ID')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total amount')),
                ('total_recipients', models.PositiveIntegerField(verbose_name='total recipients')),
                ('successful_count', models.PositiveIntegerField(default=0, verbose_name='successful count')),
                ('failed_count', models.PositiveIntegerField(default=0, verbose_name='failed count')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('PARTIAL', 'Partially Completed')], default='PENDING', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulk_payments', to='groups.chamagroup')),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_bulk_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa bulk payment',
                'verbose_name_plural': 'M-Pesa bulk payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MPesaTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='transaction ID')),
                ('merchant_request_id', models.CharField(blank=True, max_length=100, verbose_name='merchant request ID')),
                ('checkout_request_id', models.CharField(blank=True, max_length=100, verbose_name='checkout request ID')),
                ('transaction_type', models.CharField(choices=[('STK_PUSH', 'STK Push'), ('B2C', 'Business to Customer'), ('B2B', 'Business to Business'), ('C2B', 'Customer to Business')], max_length=20, verbose_name='transaction type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('phone_number', models.CharField(max_length=15, verbose_name='phone number')),
                ('account_reference', models.CharField(max_length=100, verbose_name='account reference')),
                ('transaction_desc', models.CharField(max_length=200, verbose_name='transaction description')),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, verbose_name='M-Pesa receipt number')),
                ('transaction_date', models.DateTimeField(blank=True, null=True, verbose_name='transaction date')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled'), ('TIMEOUT', 'Timeout')], default='PENDING', max_length=20, verbose_name='status')),
                ('result_code', models.CharField(blank=True, max_length=10, verbose_name='result code')),
                ('result_desc', models.TextField(blank=True, verbose_name='result description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('callback_received_at', models.DateTimeField(blank=True, null=True, verbose_name='callback received at')),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='finance.contribution')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to='groups.chamagroup')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mpesa_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'M-Pesa transaction',
                'verbose_name_plural': 'M-Pesa transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('MATCHED', 'Matched'), ('UNMATCHED', 'Unmatched'), ('DISPUTED', 'Disputed'), ('RESOLVED', 'Resolved')], default='UNMATCHED', max_length=20, verbose_name='status')),
                ('amount_difference', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='amount difference')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='reconciled at')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('contribution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='finance.contribution')),
                ('mpesa_transaction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='mpesa_integration.mpesatransaction')),
                ('reconciled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'payment reconciliation',
                'verbose_name_plural': 'payment reconciliations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['transaction_id'], name='mpesa_integ_transac_333963_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['status'], name='mpesa_integ_status_2657ed_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['phone_number'], name='mpesa_integ_phone_n_34f415_idx'),
        ),
        migrations.AddIndex(
            model_name='mpesatransaction',
            index=models.Index(fields=['created_at'], name='mpesa_integ_created_189898_idx'),
        ),
    ]
