# Generated by Django 5.2.8 on 2025-12-17 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_integration', '0002_add_uuid_fields'),
    ]

    operations = [
    ]
