# Generated by Django 5.2.8 on 2025-12-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_integration', '0003_populate_uuid_fields'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='mpesatransaction',
            new_name='mpesa_integ_uuid_958a8a_idx',
            old_name='mpesa_integ_uuid_idx',
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='checkout request ID'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='merchant_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='merchant request ID'),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='transaction ID'),
        ),
    ]
