# Generated by Django 5.2.8 on 2025-11-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoInvestmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(max_length=20, verbose_name='investment type')),
                ('minimum_balance', models.DecimalField(decimal_places=2, help_text='Minimum group balance before auto-invest', max_digits=15, verbose_name='minimum balance')),
                ('investment_percentage', models.DecimalField(decimal_places=2, help_text='Percentage of idle cash to invest', max_digits=5, verbose_name='investment percentage')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly')], max_length=20, verbose_name='frequency')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='last executed at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_auto_rules', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_investment_rules', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'auto investment rule',
                'verbose_name_plural': 'auto investment rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='principal amount')),
                ('current_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='current value')),
                ('total_returns', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='total returns')),
                ('return_percentage', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='return percentage')),
                ('days_held', models.PositiveIntegerField(verbose_name='days held')),
                ('annualized_return', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='annualized return')),
                ('recorded_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_performance', to='groups.chamagroup')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_metrics', to='investments.investment')),
            ],
            options={
                'verbose_name': 'investment performance',
                'verbose_name_plural': 'investment performance metrics',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_type', models.CharField(choices=[('TREASURY_BILL', 'Treasury Bill'), ('BOND', 'Government Bond'), ('STOCK', 'Stock'), ('MUTUAL_FUND', 'Mutual Fund'), ('FIXED_DEPOSIT', 'Fixed Deposit')], max_length=20, verbose_name='investment type')),
                ('recommended_amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='recommended amount')),
                ('expected_return', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='expected return')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Risk')], max_length=20, verbose_name='risk level')),
                ('duration_days', models.PositiveIntegerField(verbose_name='duration (days)')),
                ('confidence_score', models.DecimalField(decimal_places=2, help_text='AI confidence percentage', max_digits=5, verbose_name='confidence score')),
                ('analysis_summary', models.TextField(verbose_name='analysis summary')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('EXECUTED', 'Executed')], default='PENDING', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_recommendations', to='groups.chamagroup')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'investment recommendation',
                'verbose_name_plural': 'investment recommendations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioRebalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_allocation', models.JSONField(verbose_name='current allocation')),
                ('recommended_allocation', models.JSONField(verbose_name='recommended allocation')),
                ('rebalance_summary', models.TextField(verbose_name='rebalance summary')),
                ('expected_improvement', models.DecimalField(decimal_places=2, help_text='Expected percentage improvement', max_digits=5, verbose_name='expected improvement')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='executed at')),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='executed_rebalances', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_rebalances', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'portfolio rebalance',
                'verbose_name_plural': 'portfolio rebalances',
                'ordering': ['-created_at'],
            },
        ),
    ]
