"""
Django settings for chamahub project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
import dj_database_url

from pathlib import Path
from datetime import timedelta
from decouple import config


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-cg+((k*kk=t^*x09(3npqs0-7rg)zl&@a4eqlb8kyvvtz!-icn')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=True, cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='localhost,127.0.0.1').split(',')

# Add Render.com hostname support
RENDER_EXTERNAL_HOSTNAME = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    'auditlog',
    'drf_spectacular',
    
    # Local apps
    'accounts',
    'groups',
    'finance',
    'governance',
    'investments',
    
    # New fintech apps
    'mpesa_integration',
    'wealth_engine',
    'credit_scoring',
    'analytics_dashboard',
    'reporting_engine',
    'audit_trail',
    'kyc_verification',
    'ai_assistant',
    'automation_engine',
    'mobile_sync',
    'api_gateway',
    'gamification',
    'education_hub',
    'notifications',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'auditlog.middleware.AuditlogMiddleware',
]

ROOT_URLCONF = 'chamahub.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'chamahub.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


DATABASES = {
    'default': dj_database_url.config(
        default='sqlite:///' + str(BASE_DIR / 'db.sqlite3'),
        conn_max_age=600,
        ssl_require=True if not DEBUG else False,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Africa/Nairobi'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise configuration
WHITENOISE_AUTOREFRESH = True
WHITENOISE_USE_FINDERS = True

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'accounts.User'

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# JWT Configuration
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = config(
    'CORS_ALLOWED_ORIGINS',
    default='https://chama-hub-qe2d.onrender.com,http://localhost:3000,http://localhost:5173'
).split(',')

# Additional CORS configuration for production deployments
# This allows more flexible CORS handling when CORS_ALLOW_ALL_ORIGINS is set to True
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)

# Allowed origin regex patterns for dynamic subdomains (e.g., *.onrender.com)
CORS_ALLOWED_ORIGIN_REGEXES = []
cors_regex_patterns = config('CORS_ALLOWED_ORIGIN_REGEXES', default='')
if cors_regex_patterns:
    CORS_ALLOWED_ORIGIN_REGEXES = cors_regex_patterns.split(',')

CORS_ALLOW_CREDENTIALS = True

# CORS headers configuration - required for preflight requests
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
    'signature',  # Added for M-Pesa callback signature validation
]

# HTTP methods allowed in CORS requests
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# Headers that can be exposed to the browser
CORS_EXPOSE_HEADERS = [
    'content-type',
    'x-csrftoken',
]

# CSRF Trusted Origins
CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:5173,http://127.0.0.1:5173,https://chama-hub-qe2d.onrender.com,https://chama-hub.onrender.com'
).split(',')

# Email Configuration (Console backend for development)
EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='smtp.gmail.com')
EMAIL_PORT = config('EMAIL_PORT', default=587, cast=int)
EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=True, cast=bool)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='noreply@chamahub.com')

# Frontend URL for password reset links
FRONTEND_URL = config('FRONTEND_URL', default='http://localhost:5173')

# ============================================================================
# 📱 M-PESA DARAJA API CONFIGURATION - WITH VERIFICATION ✅
# ============================================================================

# M-Pesa Environment (sandbox for development, production for live)
MPESA_ENVIRONMENT = config('MPESA_ENVIRONMENT', default='sandbox')

# M-Pesa Daraja API Credentials
MPESA_CONSUMER_KEY = config('MPESA_CONSUMER_KEY', default='')
MPESA_CONSUMER_SECRET = config('MPESA_CONSUMER_SECRET', default='')

# 🎯 VERIFIED SANDBOX BUSINESS SHORTCODE (174379 for Safaricom sandbox)
MPESA_BUSINESS_SHORTCODE = config('MPESA_BUSINESS_SHORTCODE', default='174379')

# 🔐 CORRECT SANDBOX PASSKEY - UPDATED ✅
MPESA_PASSKEY = config('MPESA_PASSKEY', default='bfb279f9aa9bdbcf158e97dd71a467cd2e0c893059b10f78e6b72ada1ed2c919')

# Validate M-Pesa configuration on startup
if MPESA_ENVIRONMENT == 'sandbox':
    # Verify sandbox configuration
    if not MPESA_CONSUMER_KEY or not MPESA_CONSUMER_SECRET:
        print("⚠️ WARNING: M-Pesa sandbox credentials are not set. M-Pesa integration will not work.")
    
    if MPESA_BUSINESS_SHORTCODE != '174379':
        print(f"⚠️ WARNING: Using non-standard sandbox business shortcode: {MPESA_BUSINESS_SHORTCODE}")
        print("💡 TIP: For Safaricom sandbox, use '174379' as the business shortcode")

# M-Pesa Callback URLs
MPESA_CALLBACK_URL = config('MPESA_CALLBACK_URL', default='')
MPESA_SANDBOX_CALLBACK_URL = config('MPESA_SANDBOX_CALLBACK_URL', default=MPESA_CALLBACK_URL)
MPESA_PRODUCTION_CALLBACK_URL = config('MPESA_PRODUCTION_CALLBACK_URL', default=MPESA_CALLBACK_URL)

# Use appropriate callback URL based on environment
if MPESA_ENVIRONMENT == 'production':
    MPESA_CALLBACK_URL = MPESA_PRODUCTION_CALLBACK_URL
else:
    MPESA_CALLBACK_URL = MPESA_SANDBOX_CALLBACK_URL

# M-Pesa Public Key (for signature validation)
MPESA_PUBLIC_KEY = config('MPESA_PUBLIC_KEY', default='')
if MPESA_PUBLIC_KEY:
    # Replace escaped newlines with actual newlines
    MPESA_PUBLIC_KEY = MPESA_PUBLIC_KEY.replace('\\n', '\n')

# M-Pesa Transaction Limits (in KES)
MPESA_TRANSACTION_LIMIT = config('MPESA_TRANSACTION_LIMIT', default=150000, cast=int)
MPESA_DAILY_LIMIT = config('MPESA_DAILY_LIMIT', default=300000, cast=int)
MPESA_STK_PUSH_TIMEOUT = config('MPESA_STK_PUSH_TIMEOUT', default=600, cast=int)

# ============================================================================
# 🔄 CELERY & REDIS CONFIGURATION (Background Tasks)
# ============================================================================

CELERY_BROKER_URL = config('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_TIMEZONE = 'Africa/Nairobi'

# ============================================================================
# 📱 SMS & NOTIFICATIONS (Africa's Talking)
# ============================================================================

AFRICASTALKING_API_KEY = config('AFRICASTALKING_API_KEY', default='')
AFRICASTALKING_USERNAME = config('AFRICASTALKING_USERNAME', default='')
AFRICASTALKING_SENDER_ID = config('AFRICASTALKING_SENDER_ID', default='CHAMAHUB')

# ============================================================================
# 🔐 SUPERUSER ACCOUNT
# ============================================================================

ADMIN_EMAIL = config('ADMIN_EMAIL', default='')
ADMIN_PASSWORD = config('ADMIN_PASSWORD', default='')
ADMIN_PHONE = config('ADMIN_PHONE', default='')

# ============================================================================
# 🌍 THIRD-PARTY API INTEGRATIONS
# ============================================================================

# Google Maps API
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default='')

# Exchange Rate API
EXCHANGERATE_API_KEY = config('EXCHANGERATE_API_KEY', default='')

# ============================================================================
# 🚨 SECURITY & MONITORING
# ============================================================================

# Sentry Error Tracking (Optional)
SENTRY_DSN = config('SENTRY_DSN', default='')

# Logging Level
LOG_LEVEL = config('LOG_LEVEL', default='INFO')

# ============================================================================
# 💰 FINANCIAL SETTINGS
# ============================================================================

DEFAULT_CURRENCY = config('DEFAULT_CURRENCY', default='KES')
MINIMUM_CONTRIBUTION_AMOUNT = config('MINIMUM_CONTRIBUTION_AMOUNT', default=50.00, cast=float)
CONTRIBUTION_REMINDER_DAYS = config('CONTRIBUTION_REMINDER_DAYS', default=3, cast=int)

# ============================================================================
# ⚙️ PERFORMANCE SETTINGS
# ============================================================================

DATABASE_CONN_MAX_AGE = config('DATABASE_CONN_MAX_AGE', default=60, cast=int)
CACHE_TIMEOUT_MPESA_TOKEN = config('CACHE_TIMEOUT_MPESA_TOKEN', default=3000, cast=int)
CACHE_TIMEOUT_USER_SESSIONS = config('CACHE_TIMEOUT_USER_SESSIONS', default=3600, cast=int)

# ============================================================================
# 🎯 APPLICATION CONSTANTS
# ============================================================================

# Group Types
GROUP_TYPE_SAVINGS = config('GROUP_TYPE_SAVINGS', default='SAVINGS')
GROUP_TYPE_INVESTMENT = config('GROUP_TYPE_INVESTMENT', default='INVESTMENT')
GROUP_TYPE_WELFARE = config('GROUP_TYPE_WELFARE', default='WELFARE')
GROUP_TYPE_MIXED = config('GROUP_TYPE_MIXED', default='MIXED')

# Transaction Statuses
TRANSACTION_STATUS_PENDING = config('TRANSACTION_STATUS_PENDING', default='PENDING')
TRANSACTION_STATUS_SUCCESS = config('TRANSACTION_STATUS_SUCCESS', default='SUCCESS')
TRANSACTION_STATUS_FAILED = config('TRANSACTION_STATUS_FAILED', default='FAILED')
TRANSACTION_STATUS_RECONCILED = config('TRANSACTION_STATUS_RECONCILED', default='RECONCILED')

# ============================================================================
# 📊 ANALYTICS & MONITORING
# ============================================================================

# Enable/Disable Analytics Collection
ENABLE_ANALYTICS = config('ENABLE_ANALYTICS', default=True, cast=bool)
ENABLE_USER_ACTIVITY_LOGGING = config('ENABLE_USER_ACTIVITY_LOGGING', default=True, cast=bool)
ENABLE_FINANCIAL_REPORTING = config('ENABLE_FINANCIAL_REPORTING', default=True, cast=bool)

# ============================================================================
# 🎮 GAMIFICATION SETTINGS
# ============================================================================

ENABLE_GAMIFICATION = config('ENABLE_GAMIFICATION', default=True, cast=bool)
POINTS_PER_CONTRIBUTION = config('POINTS_PER_CONTRIBUTION', default=10, cast=int)
POINTS_PER_INVESTMENT = config('POINTS_PER_INVESTMENT', default=50, cast=int)
POINTS_PER_REFERRAL = config('POINTS_PER_REFERRAL', default=100, cast=int)

# ============================================================================
# 🚀 DEPLOYMENT SETTINGS
# ============================================================================

# Auto-migrate on deployment
AUTO_MIGRATE = config('AUTO_MIGRATE', default=True, cast=bool)
AUTO_COLLECTSTATIC = config('AUTO_COLLECTSTATIC', default=True, cast=bool)

# Health Check Settings
HEALTH_CHECK_ENABLED = config('HEALTH_CHECK_ENABLED', default=True, cast=bool)
HEALTH_CHECK_TIMEOUT = config('HEALTH_CHECK_TIMEOUT', default=30, cast=int)

# ============================================================================
# 🛠️ DEVELOPMENT SETTINGS (Override in production)
# ============================================================================

# For development only - disable in production
DJANGO_SUPERUSER_EMAIL = config('DJANGO_SUPERUSER_EMAIL', default='')
DJANGO_SUPERUSER_PASSWORD = config('DJANGO_SUPERUSER_PASSWORD', default='')
DJANGO_SUPERUSER_USERNAME = config('DJANGO_SUPERUSER_USERNAME', default='admin')

# Database Debug
DB_DEBUG = config('DB_DEBUG', default=False, cast=bool)

# API Documentation with drf-spectacular
SPECTACULAR_SETTINGS = {
    'TITLE': 'ChamaHub API',
    'DESCRIPTION': 'API for managing Chama (savings groups) operations including onboarding, finances, governance, and investments',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': r'/api/v[0-9]',
}

# File Upload Settings
FILE_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 5242880  # 5MB

# Logging Configuration with M-Pesa debug logging
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
        'mpesa_debug': {
            'format': '{asctime} - MPESA - {levelname} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'debug.log',
            'formatter': 'verbose',
        },
        'mpesa_file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'mpesa.log',
            'formatter': 'mpesa_debug',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.getenv('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': True,
        },
        'mpesa_integration': {
            'handlers': ['console', 'mpesa_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
        'mpesa_integration.utils': {
            'handlers': ['mpesa_file'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

# Configuration validation on startup
def validate_mpesa_configuration():
    """Validate M-Pesa configuration on startup"""
    required_configs = ['MPESA_CONSUMER_KEY', 'MPESA_CONSUMER_SECRET', 'MPESA_PASSKEY']
    missing_configs = []
    
    for config_name in required_configs:
        if not globals().get(config_name):
            missing_configs.append(config_name)
    
    if missing_configs:
        print(f"⚠️  M-Pesa Configuration Warning: Missing {', '.join(missing_configs)}")
        if MPESA_ENVIRONMENT == 'sandbox':
            print("💡 For sandbox testing, get credentials from: https://developer.safaricom.co.ke")
    else:
        print("✅ M-Pesa configuration validated successfully")
        
    # Log configuration (without sensitive data)
    safe_passkey = MPESA_PASSKEY[:10] + '...' + MPESA_PASSKEY[-10:] if MPESA_PASSKEY else 'Not set'
    print(f"📱 M-Pesa Environment: {MPESA_ENVIRONMENT}")
    print(f"🔑 Consumer Key: {'Set' if MPESA_CONSUMER_KEY else 'Not set'}")
    print(f"🔑 Consumer Secret: {'Set' if MPESA_CONSUMER_SECRET else 'Not set'}")
    print(f"🏦 Business Shortcode: {MPESA_BUSINESS_SHORTCODE}")
    print(f"🔐 Passkey: {safe_passkey}")

# Validate configuration when settings are loaded
if not os.environ.get('DJANGO_SETTINGS_MODULE', '').endswith('test'):
    validate_mpesa_configuration()