# Generated by Django 5.2.8 on 2025-11-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_type', models.CharField(max_length=100, verbose_name='achievement type')),
                ('category', models.CharField(choices=[('CONTRIBUTION', 'Contribution'), ('SAVINGS', 'Savings'), ('ENGAGEMENT', 'Engagement'), ('LEADERSHIP', 'Leadership'), ('LEARNING', 'Learning')], max_length=20, verbose_name='category')),
                ('tier', models.CharField(choices=[('BRONZE', 'Bronze'), ('SILVER', 'Silver'), ('GOLD', 'Gold'), ('PLATINUM', 'Platinum')], max_length=20, verbose_name='tier')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('points_earned', models.PositiveIntegerField(verbose_name='points earned')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='earned at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'member achievement',
                'verbose_name_plural': 'member achievements',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='RewardPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('EARNED', 'Earned'), ('REDEEMED', 'Redeemed'), ('EXPIRED', 'Expired'), ('BONUS', 'Bonus')], max_length=20, verbose_name='transaction type')),
                ('points', models.IntegerField(verbose_name='points')),
                ('balance_after', models.PositiveIntegerField(verbose_name='balance after')),
                ('reason', models.CharField(max_length=200, verbose_name='reason')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='reference ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_points', to='groups.chamagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_points', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'reward points',
                'verbose_name_plural': 'reward points',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContributionStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.PositiveIntegerField(default=0, help_text='Days/periods', verbose_name='current streak')),
                ('longest_streak', models.PositiveIntegerField(default=0, verbose_name='longest streak')),
                ('last_contribution_date', models.DateField(verbose_name='last contribution date')),
                ('streak_active', models.BooleanField(default=True, verbose_name='streak active')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='total points')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_streaks', to='groups.chamagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contribution_streaks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'contribution streak',
                'verbose_name_plural': 'contribution streaks',
                'ordering': ['-current_streak'],
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaderboard_type', models.CharField(choices=[('CONTRIBUTIONS', 'Top Contributors'), ('SAVINGS', 'Top Savers'), ('STREAKS', 'Longest Streaks'), ('POINTS', 'Most Points')], max_length=20, verbose_name='leaderboard type')),
                ('period', models.CharField(choices=[('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('ALL_TIME', 'All Time')], max_length=20, verbose_name='period')),
                ('rankings', models.JSONField(help_text='User rankings with scores', verbose_name='rankings')),
                ('period_start', models.DateField(verbose_name='period start')),
                ('period_end', models.DateField(verbose_name='period end')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='generated at')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboards', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'leaderboard',
                'verbose_name_plural': 'leaderboards',
                'ordering': ['-generated_at'],
                'unique_together': {('group', 'leaderboard_type', 'period', 'period_start')},
            },
        ),
    ]
