# Generated by Django 5.2.8 on 2025-11-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('presenter', models.CharField(max_length=200, verbose_name='presenter')),
                ('scheduled_at', models.DateTimeField(verbose_name='scheduled at')),
                ('duration_minutes', models.PositiveIntegerField(verbose_name='duration (minutes)')),
                ('meeting_url', models.URLField(blank=True, verbose_name='meeting URL')),
                ('recording_url', models.URLField(blank=True, verbose_name='recording URL')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20, verbose_name='status')),
                ('max_participants', models.PositiveIntegerField(default=100, verbose_name='max participants')),
                ('registered_count', models.PositiveIntegerField(default=0, verbose_name='registered count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'webinar',
                'verbose_name_plural': 'webinars',
                'ordering': ['-scheduled_at'],
            },
        ),
        migrations.CreateModel(
            name='EducationalContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('content_type', models.CharField(choices=[('ARTICLE', 'Article'), ('VIDEO', 'Video'), ('TUTORIAL', 'Tutorial'), ('QUIZ', 'Quiz'), ('WEBINAR', 'Webinar')], max_length=20, verbose_name='content type')),
                ('category', models.CharField(choices=[('SAVINGS', 'Savings'), ('INVESTMENTS', 'Investments'), ('LOANS', 'Loans'), ('BUDGETING', 'Budgeting'), ('FINANCIAL_PLANNING', 'Financial Planning')], max_length=30, verbose_name='category')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced')], max_length=20, verbose_name='difficulty')),
                ('description', models.TextField(verbose_name='description')),
                ('content', models.TextField(blank=True, verbose_name='content')),
                ('video_url', models.URLField(blank=True, verbose_name='video URL')),
                ('duration_minutes', models.PositiveIntegerField(help_text='Estimated completion time', verbose_name='duration (minutes)')),
                ('points_reward', models.PositiveIntegerField(default=0, verbose_name='points reward')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='views count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'educational content',
                'verbose_name_plural': 'educational content',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='target amount')),
                ('duration_days', models.PositiveIntegerField(verbose_name='duration (days)')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(verbose_name='end date')),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='UPCOMING', max_length=20, verbose_name='status')),
                ('reward_points', models.PositiveIntegerField(default=0, verbose_name='reward points')),
                ('participants_count', models.PositiveIntegerField(default=0, verbose_name='participants count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'savings challenge',
                'verbose_name_plural': 'savings challenges',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='current amount')),
                ('completed', models.BooleanField(default=False, verbose_name='completed')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='joined at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_participations', to=settings.AUTH_USER_MODEL)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='education_hub.savingschallenge')),
            ],
            options={
                'verbose_name': 'challenge participant',
                'verbose_name_plural': 'challenge participants',
                'ordering': ['-current_amount'],
                'unique_together': {('challenge', 'user')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20, verbose_name='status')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='progress percentage')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, verbose_name='time spent (minutes)')),
                ('quiz_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='quiz score')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_progress', to='education_hub.educationalcontent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user progress',
                'verbose_name_plural': 'user progress',
                'ordering': ['-started_at'],
                'unique_together': {('user', 'content')},
            },
        ),
    ]
