# Generated by Django 5.2.8 on 2025-12-18 07:29

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education_hub', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('icon_name', models.CharField(max_length=50, verbose_name='icon name')),
                ('icon_color', models.CharField(default='#FFD700', max_length=7, verbose_name='icon color')),
                ('achievement_type', models.CharField(choices=[('LEARNING', 'Learning'), ('SAVINGS', 'Savings'), ('COMMUNITY', 'Community'), ('EXPERIENCE', 'Experience'), ('SPECIAL', 'Special')], max_length=20, verbose_name='achievement type')),
                ('rarity', models.CharField(choices=[('COMMON', 'Common'), ('RARE', 'Rare'), ('EPIC', 'Epic'), ('LEGENDARY', 'Legendary')], max_length=20, verbose_name='rarity')),
                ('points_value', models.PositiveIntegerField(default=0, verbose_name='points value')),
                ('criteria_type', models.CharField(max_length=50, verbose_name='criteria type')),
                ('criteria_value', models.JSONField(help_text='JSON criteria for earning achievement', verbose_name='criteria value')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'achievement',
                'verbose_name_plural': 'achievements',
                'ordering': ['-points_value'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='certificate ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='issued at')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='valid until')),
                ('grade', models.CharField(blank=True, choices=[('PASS', 'Pass'), ('MERIT', 'Merit'), ('DISTINCTION', 'Distinction')], max_length=20, verbose_name='grade')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='score')),
                ('certificate_url', models.URLField(blank=True, verbose_name='certificate URL')),
                ('certificate_pdf', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='certificate PDF')),
                ('verification_code', models.CharField(max_length=50, unique=True, verbose_name='verification code')),
                ('is_public', models.BooleanField(default=False, verbose_name='is public')),
            ],
            options={
                'verbose_name': 'certificate',
                'verbose_name_plural': 'certificates',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True, verbose_name='completed at')),
                ('time_spent_minutes', models.PositiveIntegerField(default=0, verbose_name='time spent (minutes)')),
                ('quiz_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='quiz score')),
                ('passed', models.BooleanField(default=False, verbose_name='passed')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'content completion',
                'verbose_name_plural': 'content completions',
            },
        ),
        migrations.CreateModel(
            name='LearningPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
                ('description', models.TextField(verbose_name='description')),
                ('short_description', models.CharField(blank=True, max_length=300, verbose_name='short description')),
                ('path_type', models.CharField(choices=[('BEGINNER_FINANCIAL_LITERACY', 'Beginner Financial Literacy'), ('INVESTMENT_MASTERY', 'Investment Mastery'), ('DEBT_MANAGEMENT', 'Debt Management'), ('BUSINESS_FINANCE', 'Business Finance'), ('RETIREMENT_PLANNING', 'Retirement Planning'), ('WEALTH_BUILDING', 'Wealth Building')], max_length=50, verbose_name='path type')),
                ('icon_name', models.CharField(blank=True, max_length=50, verbose_name='icon name')),
                ('color_code', models.CharField(default='#3B82F6', max_length=7, verbose_name='color code')),
                ('total_duration_hours', models.PositiveIntegerField(default=0, verbose_name='total duration (hours)')),
                ('total_points', models.PositiveIntegerField(default=0, verbose_name='total points')),
                ('contents_count', models.PositiveIntegerField(default=0, verbose_name='contents count')),
                ('is_published', models.BooleanField(default=False, verbose_name='is published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('difficulty', models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], max_length=20, verbose_name='difficulty')),
                ('completion_badge', models.CharField(blank=True, max_length=100, verbose_name='completion badge')),
                ('completion_certificate', models.BooleanField(default=True, verbose_name='completion certificate')),
                ('enrolled_count', models.PositiveIntegerField(default=0, verbose_name='enrolled count')),
                ('completed_count', models.PositiveIntegerField(default=0, verbose_name='completed count')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'learning path',
                'verbose_name_plural': 'learning paths',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_required', models.BooleanField(default=True, verbose_name='is required')),
            ],
            options={
                'verbose_name': 'learning path content',
                'verbose_name_plural': 'learning path contents',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LearningPathEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='enrollment ID')),
                ('status', models.CharField(choices=[('ENROLLED', 'Enrolled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('DROPPED', 'Dropped'), ('PAUSED', 'Paused')], default='ENROLLED', max_length=20, verbose_name='status')),
                ('progress_percentage', models.PositiveIntegerField(default=0, verbose_name='progress percentage')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True, verbose_name='enrolled at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('last_accessed_at', models.DateTimeField(auto_now=True, verbose_name='last accessed at')),
                ('total_time_spent_minutes', models.PositiveIntegerField(default=0, verbose_name='total time spent (minutes)')),
                ('earned_points', models.PositiveIntegerField(default=0, verbose_name='earned points')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'learning path enrollment',
                'verbose_name_plural': 'learning path enrollments',
                'ordering': ['-enrolled_at'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True, verbose_name='earned at')),
                ('progress', models.PositiveIntegerField(default=0, verbose_name='progress')),
                ('is_unlocked', models.BooleanField(default=False, verbose_name='is unlocked')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'user achievement',
                'verbose_name_plural': 'user achievements',
                'ordering': ['-earned_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarPoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('options', models.JSONField(default=list, help_text='JSON array of poll options', verbose_name='options')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_multiple_choice', models.BooleanField(default=False, verbose_name='is multiple choice')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='ends at')),
            ],
            options={
                'verbose_name': 'webinar poll',
                'verbose_name_plural': 'webinar polls',
            },
        ),
        migrations.CreateModel(
            name='WebinarPollResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_options', models.JSONField(default=list, help_text='JSON array of selected option indices', verbose_name='selected options')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='submitted at')),
            ],
            options={
                'verbose_name': 'webinar poll response',
                'verbose_name_plural': 'webinar poll responses',
            },
        ),
        migrations.CreateModel(
            name='WebinarQnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(verbose_name='question')),
                ('answer', models.TextField(blank=True, verbose_name='answer')),
                ('is_anonymous', models.BooleanField(default=False, verbose_name='is anonymous')),
                ('upvotes', models.PositiveIntegerField(default=0, verbose_name='upvotes')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='answered at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'webinar Q&A',
                'verbose_name_plural': 'webinar Q&A',
                'ordering': ['-upvotes', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebinarRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='registration ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('ATTENDED', 'Attended'), ('ABSENT', 'Absent'), ('CANCELLED', 'Cancelled'), ('WAITLISTED', 'Waitlisted')], default='REGISTERED', max_length=20, verbose_name='status')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='registered at')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='joined at')),
                ('left_at', models.DateTimeField(blank=True, null=True, verbose_name='left at')),
                ('attendance_duration', models.PositiveIntegerField(default=0, verbose_name='attendance duration (minutes)')),
                ('checkin_code', models.CharField(blank=True, max_length=10, verbose_name='check-in code')),
                ('checked_in', models.BooleanField(default=False, verbose_name='checked in')),
                ('checkin_at', models.DateTimeField(blank=True, null=True, verbose_name='check-in at')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='rating')),
                ('feedback', models.TextField(blank=True, verbose_name='feedback')),
                ('feedback_at', models.DateTimeField(blank=True, null=True, verbose_name='feedback at')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='reminder sent')),
                ('followup_sent', models.BooleanField(default=False, verbose_name='follow-up sent')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='timezone')),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('MOBILE', 'Mobile'), ('INVITE', 'Invite')], default='WEB', max_length=50, verbose_name='source')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
            ],
            options={
                'verbose_name': 'webinar registration',
                'verbose_name_plural': 'webinar registrations',
                'ordering': ['-registered_at'],
            },
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='completed_lessons',
            field=models.ManyToManyField(blank=True, related_name='challenge_completions', to='education_hub.educationalcontent'),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='daily_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='daily target'),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='last_activity_at',
            field=models.DateTimeField(auto_now=True, verbose_name='last activity at'),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='learning_progress',
            field=models.PositiveIntegerField(default=0, verbose_name='learning progress'),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='notes',
            field=models.TextField(blank=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='progress_percentage',
            field=models.PositiveIntegerField(default=0, verbose_name='progress percentage'),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='started at'),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='streak_days',
            field=models.PositiveIntegerField(default=0, verbose_name='streak days'),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='target_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='target amount'),
        ),
        migrations.AddField(
            model_name='challengeparticipant',
            name='weekly_target',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='weekly target'),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='certificate_available',
            field=models.BooleanField(default=False, verbose_name='certificate available'),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='is featured'),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='learning_objectives',
            field=models.JSONField(blank=True, default=list, help_text='List of learning objectives (stored as JSON array)', verbose_name='learning objectives'),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='likes count'),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='passing_score',
            field=models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='passing score'),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='prerequisites',
            field=models.ManyToManyField(blank=True, related_name='preparation_for', to='education_hub.educationalcontent'),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='published at'),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='quiz_questions',
            field=models.JSONField(blank=True, help_text='JSON array of quiz questions with options and correct answers', null=True, verbose_name='quiz questions'),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='share_count',
            field=models.PositiveIntegerField(default=0, verbose_name='share count'),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Tags for better searchability (stored as JSON array)', verbose_name='tags'),
        ),
        migrations.AddField(
            model_name='educationalcontent',
            name='thumbnail_url',
            field=models.URLField(blank=True, verbose_name='thumbnail URL'),
        ),
        migrations.AddField(
            model_name='savingschallenge',
            name='challenge_type',
            field=models.CharField(choices=[('WEEKLY_SAVINGS', 'Weekly Savings'), ('MONTHLY_SAVINGS', 'Monthly Savings'), ('SPECIAL_EVENT', 'Special Event'), ('EMERGENCY_FUND', 'Emergency Fund'), ('INVESTMENT_CHALLENGE', 'Investment Challenge')], default='WEEKLY_SAVINGS', max_length=30, verbose_name='challenge type'),
        ),
        migrations.AddField(
            model_name='savingschallenge',
            name='educational_content',
            field=models.ManyToManyField(blank=True, related_name='challenges', to='education_hub.educationalcontent'),
        ),
        migrations.AddField(
            model_name='savingschallenge',
            name='max_participants',
            field=models.PositiveIntegerField(default=100, verbose_name='max participants'),
        ),
        migrations.AddField(
            model_name='savingschallenge',
            name='min_participants',
            field=models.PositiveIntegerField(default=1, verbose_name='min participants'),
        ),
        migrations.AddField(
            model_name='savingschallenge',
            name='reward_badge',
            field=models.CharField(blank=True, max_length=100, verbose_name='reward badge'),
        ),
        migrations.AddField(
            model_name='savingschallenge',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='savingschallenge',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='savingschallenge',
            name='success_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='success rate'),
        ),
        migrations.AddField(
            model_name='savingschallenge',
            name='total_amount_saved',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total amount saved'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='bookmarked',
            field=models.BooleanField(default=False, verbose_name='bookmarked'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='last_position',
            field=models.PositiveIntegerField(default=0, help_text='Last position in video/article', verbose_name='last position'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='quiz_answers',
            field=models.JSONField(blank=True, help_text='User answers for quiz', null=True, verbose_name='quiz answers'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='attended_count',
            field=models.PositiveIntegerField(default=0, verbose_name='attended count'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='average_rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='average rating'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='category',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('INVESTMENTS', 'Investments'), ('LOANS', 'Loans'), ('BUDGETING', 'Budgeting'), ('FINANCIAL_PLANNING', 'Financial Planning'), ('CREDIT_SCORE', 'Credit Score'), ('TAXES', 'Taxes'), ('RETIREMENT', 'Retirement'), ('INSURANCE', 'Insurance'), ('ENTREPRENEURSHIP', 'Entrepreneurship')], default='SAVINGS', max_length=30, verbose_name='category'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='certificate_available',
            field=models.BooleanField(default=True, verbose_name='certificate available'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='co_presenters',
            field=models.ManyToManyField(blank=True, related_name='co_presented_webinars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinar',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], default='BEGINNER', max_length=20, verbose_name='difficulty'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='host_url',
            field=models.URLField(blank=True, verbose_name='host URL'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='join_url',
            field=models.URLField(blank=True, verbose_name='join URL'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='meeting_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='meeting ID'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='password',
            field=models.CharField(blank=True, max_length=100, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='platform',
            field=models.CharField(choices=[('ZOOM', 'Zoom'), ('TEAMS', 'Microsoft Teams'), ('GOOGLE_MEET', 'Google Meet'), ('JITSI', 'Jitsi'), ('CUSTOM', 'Custom Platform')], default='ZOOM', max_length=20, verbose_name='platform'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='points_reward',
            field=models.PositiveIntegerField(default=10, verbose_name='points reward'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='poll_enabled',
            field=models.BooleanField(default=False, verbose_name='poll enabled'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='qna_enabled',
            field=models.BooleanField(default=True, verbose_name='Q&A enabled'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='recording_available_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='recording available at'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='recording_password',
            field=models.CharField(blank=True, max_length=100, verbose_name='recording password'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='related_content',
            field=models.ManyToManyField(blank=True, related_name='webinars', to='education_hub.educationalcontent'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='resources_url',
            field=models.URLField(blank=True, verbose_name='resources URL'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='short_description',
            field=models.CharField(blank=True, max_length=300, verbose_name='short description'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='slides_url',
            field=models.URLField(blank=True, verbose_name='slides URL'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='slug'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='timezone',
            field=models.CharField(default='UTC', max_length=50, verbose_name='timezone'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='views count'),
        ),
        migrations.AlterField(
            model_name='educationalcontent',
            name='category',
            field=models.CharField(choices=[('SAVINGS', 'Savings'), ('INVESTMENTS', 'Investments'), ('LOANS', 'Loans'), ('BUDGETING', 'Budgeting'), ('FINANCIAL_PLANNING', 'Financial Planning'), ('CREDIT_SCORE', 'Credit Score'), ('TAXES', 'Taxes'), ('RETIREMENT', 'Retirement'), ('INSURANCE', 'Insurance'), ('ENTREPRENEURSHIP', 'Entrepreneurship')], max_length=30, verbose_name='category'),
        ),
        migrations.AlterField(
            model_name='educationalcontent',
            name='content_type',
            field=models.CharField(choices=[('ARTICLE', 'Article'), ('VIDEO', 'Video'), ('TUTORIAL', 'Tutorial'), ('QUIZ', 'Quiz'), ('WEBINAR', 'Webinar'), ('COURSE', 'Course'), ('EBOOK', 'E-Book')], max_length=20, verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='educationalcontent',
            name='difficulty',
            field=models.CharField(choices=[('BEGINNER', 'Beginner'), ('INTERMEDIATE', 'Intermediate'), ('ADVANCED', 'Advanced'), ('EXPERT', 'Expert')], max_length=20, verbose_name='difficulty'),
        ),
        migrations.AlterField(
            model_name='savingschallenge',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challenges', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='savingschallenge',
            name='status',
            field=models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ARCHIVED', 'Archived')], default='UPCOMING', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REVIEWING', 'Reviewing')], default='NOT_STARTED', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='presenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presented_webinars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='webinar',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('RECORDING_AVAILABLE', 'Recording Available')], default='SCHEDULED', max_length=20, verbose_name='status'),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['category', 'difficulty'], name='education_h_categor_5f196c_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['is_published', 'is_featured'], name='education_h_is_publ_f1297f_idx'),
        ),
        migrations.AddIndex(
            model_name='educationalcontent',
            index=models.Index(fields=['views_count'], name='education_h_views_c_97b00e_idx'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates_awarded', to='education_hub.educationalcontent'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentcompletion',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completion_records', to='education_hub.educationalcontent'),
        ),
        migrations.AddField(
            model_name='certificate',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificates_awarded', to='education_hub.learningpath'),
        ),
        migrations.AddField(
            model_name='savingschallenge',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='challenges', to='education_hub.learningpath'),
        ),
        migrations.AddField(
            model_name='webinar',
            name='learning_path',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webinars', to='education_hub.learningpath'),
        ),
        migrations.AddField(
            model_name='learningpathcontent',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_assignments', to='education_hub.educationalcontent'),
        ),
        migrations.AddField(
            model_name='learningpathcontent',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_contents', to='education_hub.learningpath'),
        ),
        migrations.AddField(
            model_name='learningpath',
            name='learning_path_contents',
            field=models.ManyToManyField(related_name='learning_paths', through='education_hub.LearningPathContent', to='education_hub.educationalcontent'),
        ),
        migrations.AddField(
            model_name='learningpathenrollment',
            name='completed_contents',
            field=models.ManyToManyField(related_name='completed_by', through='education_hub.ContentCompletion', to='education_hub.educationalcontent'),
        ),
        migrations.AddField(
            model_name='learningpathenrollment',
            name='current_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_enrollments', to='education_hub.educationalcontent'),
        ),
        migrations.AddField(
            model_name='learningpathenrollment',
            name='learning_path',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='education_hub.learningpath'),
        ),
        migrations.AddField(
            model_name='learningpathenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentcompletion',
            name='enrollment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='education_hub.learningpathenrollment'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='achievement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to='education_hub.achievement'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='context_challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education_hub.savingschallenge'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='context_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education_hub.educationalcontent'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='context_webinar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='education_hub.webinar'),
        ),
        migrations.AddField(
            model_name='userachievement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_achievements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinarpoll',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinarpoll',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='education_hub.webinar'),
        ),
        migrations.AddField(
            model_name='webinarpollresponse',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='education_hub.webinarpoll'),
        ),
        migrations.AddField(
            model_name='webinarpollresponse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinarqna',
            name='answered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinarqna',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_questions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinarqna',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='education_hub.webinar'),
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webinar_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='webinarregistration',
            name='webinar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='education_hub.webinar'),
        ),
        migrations.AlterUniqueTogether(
            name='learningpathcontent',
            unique_together={('learning_path', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='learningpathenrollment',
            unique_together={('user', 'learning_path')},
        ),
        migrations.AlterUniqueTogether(
            name='contentcompletion',
            unique_together={('enrollment', 'content')},
        ),
        migrations.AlterUniqueTogether(
            name='userachievement',
            unique_together={('user', 'achievement')},
        ),
        migrations.AlterUniqueTogether(
            name='webinarpollresponse',
            unique_together={('poll', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='webinarregistration',
            unique_together={('webinar', 'user')},
        ),
    ]
