# Generated by Django 5.2.8 on 2025-12-10 08:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_groupmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System'), ('FINANCE', 'Finance'), ('LOAN', 'Loan'), ('CONTRIBUTION', 'Contribution'), ('MEETING', 'Meeting'), ('INVESTMENT', 'Investment'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('target_all_users', models.BooleanField(default=False)),
                ('total_recipients', models.PositiveIntegerField(default=0)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('read_count', models.PositiveIntegerField(default=0)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, to='groups.chamagroup')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_bulk_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_contributions', models.BooleanField(default=True)),
                ('email_loans', models.BooleanField(default=True)),
                ('email_investments', models.BooleanField(default=True)),
                ('email_meetings', models.BooleanField(default=True)),
                ('email_system', models.BooleanField(default=True)),
                ('inapp_contributions', models.BooleanField(default=True)),
                ('inapp_loans', models.BooleanField(default=True)),
                ('inapp_investments', models.BooleanField(default=True)),
                ('inapp_meetings', models.BooleanField(default=True)),
                ('inapp_system', models.BooleanField(default=True)),
                ('push_contributions', models.BooleanField(default=False)),
                ('push_loans', models.BooleanField(default=False)),
                ('push_investments', models.BooleanField(default=False)),
                ('push_meetings', models.BooleanField(default=False)),
                ('push_system', models.BooleanField(default=False)),
                ('daily_digest', models.BooleanField(default=True)),
                ('weekly_digest', models.BooleanField(default=False)),
                ('digest_time', models.TimeField(default='18:00')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True)),
                ('quiet_hours_end', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('SYSTEM', 'System'), ('FINANCE', 'Finance'), ('LOAN', 'Loan'), ('CONTRIBUTION', 'Contribution'), ('MEETING', 'Meeting'), ('INVESTMENT', 'Investment'), ('GENERAL', 'General')], default='GENERAL', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('related_object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.chamagroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', 'created_at'], name='notificatio_user_id_c62b26_idx'), models.Index(fields=['group', 'created_at'], name='notificatio_group_i_1fda94_idx')],
            },
        ),
    ]
