# Generated by Django 5.2.8 on 2025-11-18 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS'), ('PUSH', 'Push Notification'), ('IN_APP', 'In-App')], max_length=20, verbose_name='channel')),
                ('subject_template', models.CharField(blank=True, max_length=200, verbose_name='subject template')),
                ('body_template', models.TextField(verbose_name='body template')),
                ('variables', models.JSONField(default=list, help_text='Template variables', verbose_name='variables')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'notification template',
                'verbose_name_plural': 'notification templates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AutomationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_type', models.CharField(choices=[('RECURRING_CONTRIBUTION', 'Recurring Contribution'), ('LATE_FEE', 'Late Fee Calculation'), ('DIVIDEND_DISTRIBUTION', 'Dividend Distribution'), ('NOTIFICATION', 'Notification'), ('REMINDER', 'Reminder')], max_length=30, verbose_name='rule type')),
                ('rule_name', models.CharField(max_length=200, verbose_name='rule name')),
                ('description', models.TextField(verbose_name='description')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily'), ('WEEKLY', 'Weekly'), ('MONTHLY', 'Monthly'), ('QUARTERLY', 'Quarterly'), ('CUSTOM', 'Custom')], max_length=20, verbose_name='frequency')),
                ('conditions', models.JSONField(help_text='Rule execution conditions', verbose_name='conditions')),
                ('actions', models.JSONField(help_text='Actions to perform', verbose_name='actions')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='last executed at')),
                ('next_execution_at', models.DateTimeField(verbose_name='next execution at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automation_rules', to='groups.chamagroup')),
            ],
            options={
                'verbose_name': 'automation rule',
                'verbose_name_plural': 'automation rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PARTIAL', 'Partially Completed')], max_length=20, verbose_name='status')),
                ('executed_at', models.DateTimeField(auto_now_add=True, verbose_name='executed at')),
                ('duration_ms', models.PositiveIntegerField(verbose_name='duration (ms)')),
                ('result_data', models.JSONField(default=dict, verbose_name='result data')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='execution_logs', to='automation_engine.automationrule')),
            ],
            options={
                'verbose_name': 'execution log',
                'verbose_name_plural': 'execution logs',
                'ordering': ['-executed_at'],
            },
        ),
    ]
